# Generated by Django 3.1.4 on 2020-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201224_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
