# Generated by Django 3.1.4 on 2021-01-11 13:53
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210111_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, # noqa
                                    to='home.teacher'),
        ),
    ]
