# Generated by Django 3.1.5 on 2021-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210114_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccy', models.CharField(max_length=200)),
                ('base_ccy', models.CharField(max_length=200)),
                ('buy', models.CharField(max_length=200)),
                ('sale', models.CharField(max_length=200)),
            ],
        ),
    ]
