# Generated by Django 3.1.5 on 2021-03-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210312_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='picture',
        ),
    ]
