# Generated by Django 3.1.5 on 2021-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210312_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
